name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./script

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Download depots and gamedata
        run: python3 ./download.py
